//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 11:11:49 AM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoriesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoriesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryCategoryDetails" type="{}PrimaryCategoryDetailsType" minOccurs="0"/>
 *         &lt;element name="SecondaryCategoryDetails" type="{}SecondaryCategoryDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoriesType", propOrder = {
    "primaryCategoryDetails",
    "secondaryCategoryDetails"
})
public class CategoriesType
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "PrimaryCategoryDetails")
    protected PrimaryCategoryDetailsType primaryCategoryDetails;
    @XmlElement(name = "SecondaryCategoryDetails")
    protected SecondaryCategoryDetailsType secondaryCategoryDetails;

    /**
     * Gets the value of the primaryCategoryDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryCategoryDetailsType }
     *     
     */
    public PrimaryCategoryDetailsType getPrimaryCategoryDetails() {
        return primaryCategoryDetails;
    }

    /**
     * Sets the value of the primaryCategoryDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryCategoryDetailsType }
     *     
     */
    public void setPrimaryCategoryDetails(PrimaryCategoryDetailsType value) {
        this.primaryCategoryDetails = value;
    }

    public boolean isSetPrimaryCategoryDetails() {
        return (this.primaryCategoryDetails!= null);
    }

    /**
     * Gets the value of the secondaryCategoryDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SecondaryCategoryDetailsType }
     *     
     */
    public SecondaryCategoryDetailsType getSecondaryCategoryDetails() {
        return secondaryCategoryDetails;
    }

    /**
     * Sets the value of the secondaryCategoryDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecondaryCategoryDetailsType }
     *     
     */
    public void setSecondaryCategoryDetails(SecondaryCategoryDetailsType value) {
        this.secondaryCategoryDetails = value;
    }

    public boolean isSetSecondaryCategoryDetails() {
        return (this.secondaryCategoryDetails!= null);
    }

}
