//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 11:11:49 AM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TotalVouchers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Vouchers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Voucher" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ItemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="VoucherId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="OrderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="OfferSiteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="BuyerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="BuyerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PaymentDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RedeemedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="CancelledDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ValidUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="CheckIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="CheckOut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProductOffer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Errors" type="{}ErrorsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ack",
    "objectId",
    "totalVouchers",
    "vouchers",
    "errors"
})
@XmlRootElement(name = "ListOfVouchersRS")
public class ListOfVouchersRS
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "Ack", required = true)
    protected String ack;
    @XmlElement(name = "ObjectId")
    protected Integer objectId;
    @XmlElement(name = "TotalVouchers", defaultValue = "null")
    protected Integer totalVouchers;
    @XmlElement(name = "Vouchers")
    protected ListOfVouchersRS.Vouchers vouchers;
    @XmlElement(name = "Errors")
    protected ErrorsType errors;
    @XmlAttribute(name = "TimeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAck(String value) {
        this.ack = value;
    }

    public boolean isSetAck() {
        return (this.ack!= null);
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObjectId(Integer value) {
        this.objectId = value;
    }

    public boolean isSetObjectId() {
        return (this.objectId!= null);
    }

    /**
     * Gets the value of the totalVouchers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalVouchers() {
        return totalVouchers;
    }

    /**
     * Sets the value of the totalVouchers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalVouchers(Integer value) {
        this.totalVouchers = value;
    }

    public boolean isSetTotalVouchers() {
        return (this.totalVouchers!= null);
    }

    /**
     * Gets the value of the vouchers property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfVouchersRS.Vouchers }
     *     
     */
    public ListOfVouchersRS.Vouchers getVouchers() {
        return vouchers;
    }

    /**
     * Sets the value of the vouchers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfVouchersRS.Vouchers }
     *     
     */
    public void setVouchers(ListOfVouchersRS.Vouchers value) {
        this.vouchers = value;
    }

    public boolean isSetVouchers() {
        return (this.vouchers!= null);
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    public boolean isSetErrors() {
        return (this.errors!= null);
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    public boolean isSetTimeStamp() {
        return (this.timeStamp!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Voucher" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ItemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="VoucherId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="OrderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="OfferSiteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="BuyerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="BuyerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PaymentDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RedeemedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="CancelledDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ValidUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="CheckIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="CheckOut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProductOffer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "voucher"
    })
    public static class Vouchers
        implements Serializable
    {

        private final static long serialVersionUID = 20070801L;
        @XmlElement(name = "Voucher")
        protected List<ListOfVouchersRS.Vouchers.Voucher> voucher;

        /**
         * Gets the value of the voucher property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the voucher property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVoucher().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ListOfVouchersRS.Vouchers.Voucher }
         * 
         * 
         */
        public List<ListOfVouchersRS.Vouchers.Voucher> getVoucher() {
            if (voucher == null) {
                voucher = new ArrayList<ListOfVouchersRS.Vouchers.Voucher>();
            }
            return this.voucher;
        }

        public boolean isSetVoucher() {
            return ((this.voucher!= null)&&(!this.voucher.isEmpty()));
        }

        public void unsetVoucher() {
            this.voucher = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ItemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="VoucherId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="OrderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="OfferSiteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="BuyerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="BuyerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PaymentDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RedeemedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="CancelledDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ValidUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="CheckIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="CheckOut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProductOffer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemId",
            "voucherId",
            "orderId",
            "offerSiteId",
            "status",
            "buyerId",
            "buyerName",
            "paymentDate",
            "redeemedDate",
            "cancelledDate",
            "validUntil",
            "checkIn",
            "checkOut",
            "price",
            "currency",
            "productOffer"
        })
        public static class Voucher
            implements Serializable
        {

            private final static long serialVersionUID = 20070801L;
            @XmlElement(name = "ItemId")
            protected String itemId;
            @XmlElement(name = "VoucherId")
            protected String voucherId;
            @XmlElement(name = "OrderId")
            protected String orderId;
            @XmlElement(name = "OfferSiteId", defaultValue = "null")
            protected String offerSiteId;
            @XmlElement(name = "Status", defaultValue = "null")
            protected Integer status;
            @XmlElement(name = "BuyerId")
            protected String buyerId;
            @XmlElement(name = "BuyerName")
            protected String buyerName;
            @XmlElement(name = "PaymentDate")
            protected String paymentDate;
            @XmlElement(name = "RedeemedDate")
            protected String redeemedDate;
            @XmlElement(name = "CancelledDate")
            protected String cancelledDate;
            @XmlElement(name = "ValidUntil")
            protected String validUntil;
            @XmlElement(name = "CheckIn")
            protected String checkIn;
            @XmlElement(name = "CheckOut")
            protected String checkOut;
            @XmlElement(name = "Price")
            protected String price;
            @XmlElement(name = "Currency")
            protected String currency;
            @XmlElement(name = "ProductOffer")
            protected String productOffer;

            /**
             * Gets the value of the itemId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemId() {
                return itemId;
            }

            /**
             * Sets the value of the itemId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemId(String value) {
                this.itemId = value;
            }

            public boolean isSetItemId() {
                return (this.itemId!= null);
            }

            /**
             * Gets the value of the voucherId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVoucherId() {
                return voucherId;
            }

            /**
             * Sets the value of the voucherId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVoucherId(String value) {
                this.voucherId = value;
            }

            public boolean isSetVoucherId() {
                return (this.voucherId!= null);
            }

            /**
             * Gets the value of the orderId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderId() {
                return orderId;
            }

            /**
             * Sets the value of the orderId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderId(String value) {
                this.orderId = value;
            }

            public boolean isSetOrderId() {
                return (this.orderId!= null);
            }

            /**
             * Gets the value of the offerSiteId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOfferSiteId() {
                return offerSiteId;
            }

            /**
             * Sets the value of the offerSiteId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOfferSiteId(String value) {
                this.offerSiteId = value;
            }

            public boolean isSetOfferSiteId() {
                return (this.offerSiteId!= null);
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStatus(Integer value) {
                this.status = value;
            }

            public boolean isSetStatus() {
                return (this.status!= null);
            }

            /**
             * Gets the value of the buyerId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerId() {
                return buyerId;
            }

            /**
             * Sets the value of the buyerId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerId(String value) {
                this.buyerId = value;
            }

            public boolean isSetBuyerId() {
                return (this.buyerId!= null);
            }

            /**
             * Gets the value of the buyerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerName() {
                return buyerName;
            }

            /**
             * Sets the value of the buyerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerName(String value) {
                this.buyerName = value;
            }

            public boolean isSetBuyerName() {
                return (this.buyerName!= null);
            }

            /**
             * Gets the value of the paymentDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPaymentDate() {
                return paymentDate;
            }

            /**
             * Sets the value of the paymentDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaymentDate(String value) {
                this.paymentDate = value;
            }

            public boolean isSetPaymentDate() {
                return (this.paymentDate!= null);
            }

            /**
             * Gets the value of the redeemedDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRedeemedDate() {
                return redeemedDate;
            }

            /**
             * Sets the value of the redeemedDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRedeemedDate(String value) {
                this.redeemedDate = value;
            }

            public boolean isSetRedeemedDate() {
                return (this.redeemedDate!= null);
            }

            /**
             * Gets the value of the cancelledDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCancelledDate() {
                return cancelledDate;
            }

            /**
             * Sets the value of the cancelledDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCancelledDate(String value) {
                this.cancelledDate = value;
            }

            public boolean isSetCancelledDate() {
                return (this.cancelledDate!= null);
            }

            /**
             * Gets the value of the validUntil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValidUntil() {
                return validUntil;
            }

            /**
             * Sets the value of the validUntil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValidUntil(String value) {
                this.validUntil = value;
            }

            public boolean isSetValidUntil() {
                return (this.validUntil!= null);
            }

            /**
             * Gets the value of the checkIn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCheckIn() {
                return checkIn;
            }

            /**
             * Sets the value of the checkIn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCheckIn(String value) {
                this.checkIn = value;
            }

            public boolean isSetCheckIn() {
                return (this.checkIn!= null);
            }

            /**
             * Gets the value of the checkOut property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCheckOut() {
                return checkOut;
            }

            /**
             * Sets the value of the checkOut property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCheckOut(String value) {
                this.checkOut = value;
            }

            public boolean isSetCheckOut() {
                return (this.checkOut!= null);
            }

            /**
             * Gets the value of the price property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrice(String value) {
                this.price = value;
            }

            public boolean isSetPrice() {
                return (this.price!= null);
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            public boolean isSetCurrency() {
                return (this.currency!= null);
            }

            /**
             * Gets the value of the productOffer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductOffer() {
                return productOffer;
            }

            /**
             * Sets the value of the productOffer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductOffer(String value) {
                this.productOffer = value;
            }

            public boolean isSetProductOffer() {
                return (this.productOffer!= null);
            }

        }

    }

}
