//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 11:11:49 AM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Ack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SellerAccounts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SellerAccount" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sellerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="SellerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PayeeAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Products">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Product" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="validities">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Categories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Category" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShopCategories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ShopCategory" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ParentCategoryId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Errors" type="{}ErrorsType" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ack",
    "objectId",
    "sellerAccounts",
    "products",
    "categories",
    "shopCategories",
    "errors"
})
@XmlRootElement(name = "ObjectMetaDataRS")
public class ObjectMetaDataRS
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "Ack")
    protected String ack;
    @XmlElement(name = "ObjectId")
    protected Integer objectId;
    @XmlElement(name = "SellerAccounts")
    protected ObjectMetaDataRS.SellerAccounts sellerAccounts;
    @XmlElement(name = "Products")
    protected ObjectMetaDataRS.Products products;
    @XmlElement(name = "Categories")
    protected ObjectMetaDataRS.Categories categories;
    @XmlElement(name = "ShopCategories")
    protected ObjectMetaDataRS.ShopCategories shopCategories;
    @XmlElement(name = "Errors")
    protected ErrorsType errors;
    @XmlAttribute(name = "TimeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAck(String value) {
        this.ack = value;
    }

    public boolean isSetAck() {
        return (this.ack!= null);
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObjectId(Integer value) {
        this.objectId = value;
    }

    public boolean isSetObjectId() {
        return (this.objectId!= null);
    }

    /**
     * Gets the value of the sellerAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMetaDataRS.SellerAccounts }
     *     
     */
    public ObjectMetaDataRS.SellerAccounts getSellerAccounts() {
        return sellerAccounts;
    }

    /**
     * Sets the value of the sellerAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMetaDataRS.SellerAccounts }
     *     
     */
    public void setSellerAccounts(ObjectMetaDataRS.SellerAccounts value) {
        this.sellerAccounts = value;
    }

    public boolean isSetSellerAccounts() {
        return (this.sellerAccounts!= null);
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMetaDataRS.Products }
     *     
     */
    public ObjectMetaDataRS.Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMetaDataRS.Products }
     *     
     */
    public void setProducts(ObjectMetaDataRS.Products value) {
        this.products = value;
    }

    public boolean isSetProducts() {
        return (this.products!= null);
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMetaDataRS.Categories }
     *     
     */
    public ObjectMetaDataRS.Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMetaDataRS.Categories }
     *     
     */
    public void setCategories(ObjectMetaDataRS.Categories value) {
        this.categories = value;
    }

    public boolean isSetCategories() {
        return (this.categories!= null);
    }

    /**
     * Gets the value of the shopCategories property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMetaDataRS.ShopCategories }
     *     
     */
    public ObjectMetaDataRS.ShopCategories getShopCategories() {
        return shopCategories;
    }

    /**
     * Sets the value of the shopCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMetaDataRS.ShopCategories }
     *     
     */
    public void setShopCategories(ObjectMetaDataRS.ShopCategories value) {
        this.shopCategories = value;
    }

    public boolean isSetShopCategories() {
        return (this.shopCategories!= null);
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    public boolean isSetErrors() {
        return (this.errors!= null);
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    public boolean isSetTimeStamp() {
        return (this.timeStamp!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Category" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category"
    })
    public static class Categories
        implements Serializable
    {

        private final static long serialVersionUID = 20070801L;
        @XmlElement(name = "Category")
        protected List<ObjectMetaDataRS.Categories.Category> category;

        /**
         * Gets the value of the category property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectMetaDataRS.Categories.Category }
         * 
         * 
         */
        public List<ObjectMetaDataRS.Categories.Category> getCategory() {
            if (category == null) {
                category = new ArrayList<ObjectMetaDataRS.Categories.Category>();
            }
            return this.category;
        }

        public boolean isSetCategory() {
            return ((this.category!= null)&&(!this.category.isEmpty()));
        }

        public void unsetCategory() {
            this.category = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name"
        })
        public static class Category
            implements Serializable
        {

            private final static long serialVersionUID = 20070801L;
            @XmlElement(name = "Id")
            protected int id;
            @XmlElement(name = "Name", required = true)
            protected String name;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            public boolean isSetId() {
                return true;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            public boolean isSetName() {
                return (this.name!= null);
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Product" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="validities">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "product"
    })
    public static class Products
        implements Serializable
    {

        private final static long serialVersionUID = 20070801L;
        @XmlElement(name = "Product")
        protected List<ObjectMetaDataRS.Products.Product> product;

        /**
         * Gets the value of the product property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProduct().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectMetaDataRS.Products.Product }
         * 
         * 
         */
        public List<ObjectMetaDataRS.Products.Product> getProduct() {
            if (product == null) {
                product = new ArrayList<ObjectMetaDataRS.Products.Product>();
            }
            return this.product;
        }

        public boolean isSetProduct() {
            return ((this.product!= null)&&(!this.product.isEmpty()));
        }

        public void unsetProduct() {
            this.product = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="validities">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name",
            "validities"
        })
        public static class Product
            implements Serializable
        {

            private final static long serialVersionUID = 20070801L;
            @XmlElement(name = "Id")
            protected long id;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(required = true)
            protected ObjectMetaDataRS.Products.Product.Validities validities;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            public boolean isSetId() {
                return true;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            public boolean isSetName() {
                return (this.name!= null);
            }

            /**
             * Gets the value of the validities property.
             * 
             * @return
             *     possible object is
             *     {@link ObjectMetaDataRS.Products.Product.Validities }
             *     
             */
            public ObjectMetaDataRS.Products.Product.Validities getValidities() {
                return validities;
            }

            /**
             * Sets the value of the validities property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObjectMetaDataRS.Products.Product.Validities }
             *     
             */
            public void setValidities(ObjectMetaDataRS.Products.Product.Validities value) {
                this.validities = value;
            }

            public boolean isSetValidities() {
                return (this.validities!= null);
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "validity"
            })
            public static class Validities
                implements Serializable
            {

                private final static long serialVersionUID = 20070801L;
                protected List<String> validity;

                /**
                 * Gets the value of the validity property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the validity property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getValidity().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getValidity() {
                    if (validity == null) {
                        validity = new ArrayList<String>();
                    }
                    return this.validity;
                }

                public boolean isSetValidity() {
                    return ((this.validity!= null)&&(!this.validity.isEmpty()));
                }

                public void unsetValidity() {
                    this.validity = null;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SellerAccount" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sellerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="SellerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PayeeAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sellerAccount"
    })
    public static class SellerAccounts
        implements Serializable
    {

        private final static long serialVersionUID = 20070801L;
        @XmlElement(name = "SellerAccount")
        protected List<ObjectMetaDataRS.SellerAccounts.SellerAccount> sellerAccount;

        /**
         * Gets the value of the sellerAccount property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sellerAccount property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSellerAccount().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectMetaDataRS.SellerAccounts.SellerAccount }
         * 
         * 
         */
        public List<ObjectMetaDataRS.SellerAccounts.SellerAccount> getSellerAccount() {
            if (sellerAccount == null) {
                sellerAccount = new ArrayList<ObjectMetaDataRS.SellerAccounts.SellerAccount>();
            }
            return this.sellerAccount;
        }

        public boolean isSetSellerAccount() {
            return ((this.sellerAccount!= null)&&(!this.sellerAccount.isEmpty()));
        }

        public void unsetSellerAccount() {
            this.sellerAccount = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sellerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="SellerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PayeeAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sellerId",
            "sellerName",
            "payeeAccount"
        })
        public static class SellerAccount
            implements Serializable
        {

            private final static long serialVersionUID = 20070801L;
            protected long sellerId;
            @XmlElement(name = "SellerName", required = true)
            protected String sellerName;
            @XmlElement(name = "PayeeAccount", required = true)
            protected String payeeAccount;

            /**
             * Gets the value of the sellerId property.
             * 
             */
            public long getSellerId() {
                return sellerId;
            }

            /**
             * Sets the value of the sellerId property.
             * 
             */
            public void setSellerId(long value) {
                this.sellerId = value;
            }

            public boolean isSetSellerId() {
                return true;
            }

            /**
             * Gets the value of the sellerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSellerName() {
                return sellerName;
            }

            /**
             * Sets the value of the sellerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSellerName(String value) {
                this.sellerName = value;
            }

            public boolean isSetSellerName() {
                return (this.sellerName!= null);
            }

            /**
             * Gets the value of the payeeAccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayeeAccount() {
                return payeeAccount;
            }

            /**
             * Sets the value of the payeeAccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayeeAccount(String value) {
                this.payeeAccount = value;
            }

            public boolean isSetPayeeAccount() {
                return (this.payeeAccount!= null);
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ShopCategory" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ParentCategoryId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shopCategory"
    })
    public static class ShopCategories
        implements Serializable
    {

        private final static long serialVersionUID = 20070801L;
        @XmlElement(name = "ShopCategory")
        protected List<ObjectMetaDataRS.ShopCategories.ShopCategory> shopCategory;

        /**
         * Gets the value of the shopCategory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shopCategory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShopCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectMetaDataRS.ShopCategories.ShopCategory }
         * 
         * 
         */
        public List<ObjectMetaDataRS.ShopCategories.ShopCategory> getShopCategory() {
            if (shopCategory == null) {
                shopCategory = new ArrayList<ObjectMetaDataRS.ShopCategories.ShopCategory>();
            }
            return this.shopCategory;
        }

        public boolean isSetShopCategory() {
            return ((this.shopCategory!= null)&&(!this.shopCategory.isEmpty()));
        }

        public void unsetShopCategory() {
            this.shopCategory = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ParentCategoryId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name",
            "parentCategoryId"
        })
        public static class ShopCategory
            implements Serializable
        {

            private final static long serialVersionUID = 20070801L;
            @XmlElement(name = "Id")
            protected int id;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "ParentCategoryId")
            protected long parentCategoryId;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            public boolean isSetId() {
                return true;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            public boolean isSetName() {
                return (this.name!= null);
            }

            /**
             * Gets the value of the parentCategoryId property.
             * 
             */
            public long getParentCategoryId() {
                return parentCategoryId;
            }

            /**
             * Sets the value of the parentCategoryId property.
             * 
             */
            public void setParentCategoryId(long value) {
                this.parentCategoryId = value;
            }

            public boolean isSetParentCategoryId() {
                return true;
            }

        }

    }

}
