//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 11:11:49 AM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimaryCategoryDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrimaryCategoryDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryCategoryId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryItemSpecifics" type="{}PrimaryItemSpecificsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrimaryCategoryDetailsType", propOrder = {
    "primaryCategoryId",
    "primaryItemSpecifics"
})
public class PrimaryCategoryDetailsType
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "PrimaryCategoryId")
    protected String primaryCategoryId;
    @XmlElement(name = "PrimaryItemSpecifics")
    protected PrimaryItemSpecificsType primaryItemSpecifics;

    /**
     * Gets the value of the primaryCategoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryCategoryId() {
        return primaryCategoryId;
    }

    /**
     * Sets the value of the primaryCategoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryCategoryId(String value) {
        this.primaryCategoryId = value;
    }

    public boolean isSetPrimaryCategoryId() {
        return (this.primaryCategoryId!= null);
    }

    /**
     * Gets the value of the primaryItemSpecifics property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryItemSpecificsType }
     *     
     */
    public PrimaryItemSpecificsType getPrimaryItemSpecifics() {
        return primaryItemSpecifics;
    }

    /**
     * Sets the value of the primaryItemSpecifics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryItemSpecificsType }
     *     
     */
    public void setPrimaryItemSpecifics(PrimaryItemSpecificsType value) {
        this.primaryItemSpecifics = value;
    }

    public boolean isSetPrimaryItemSpecifics() {
        return (this.primaryItemSpecifics!= null);
    }

}
