//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 11:11:49 AM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DesignTemplate" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SiteId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ShopObjectId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TemplateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Categories" type="{}CategoriesType" minOccurs="0"/>
 *         &lt;element name="StoreCategories" type="{}StoreCategoriesType" minOccurs="0"/>
 *         &lt;element name="OfferTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OfferSubTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="RetailPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amenities" type="{}AmenitiesType" minOccurs="0"/>
 *         &lt;element name="Properties" type="{}PropertiesType" minOccurs="0"/>
 *         &lt;element name="PictureDetails" type="{}PictureDetailsType"/>
 *         &lt;element name="AdditionalOptions" type="{}AdditionalOptionsType" minOccurs="0"/>
 *         &lt;element name="Description" type="{}DescriptionType"/>
 *         &lt;element name="DescriptionPictures" type="{}DescriptionPicturesType"/>
 *         &lt;element name="VoucherValidity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Errors" type="{}ErrorsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ack",
    "designTemplate",
    "siteId",
    "shopObjectId",
    "templateName",
    "productId",
    "categories",
    "storeCategories",
    "offerTitle",
    "offerSubTitle",
    "price",
    "retailPrice",
    "currency",
    "amenities",
    "properties",
    "pictureDetails",
    "additionalOptions",
    "description",
    "descriptionPictures",
    "voucherValidity",
    "errors"
})
@XmlRootElement(name = "TemplateDetailsRS")
public class TemplateDetailsRS
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "Ack", required = true)
    protected String ack;
    @XmlElement(name = "DesignTemplate", defaultValue = "null")
    protected Integer designTemplate;
    @XmlElement(name = "SiteId", defaultValue = "null")
    protected Integer siteId;
    @XmlElement(name = "ShopObjectId")
    protected String shopObjectId;
    @XmlElement(name = "TemplateName", required = true)
    protected String templateName;
    @XmlElement(name = "ProductId", defaultValue = "null")
    protected Integer productId;
    @XmlElement(name = "Categories")
    protected CategoriesType categories;
    @XmlElement(name = "StoreCategories")
    protected StoreCategoriesType storeCategories;
    @XmlElement(name = "OfferTitle", required = true)
    protected String offerTitle;
    @XmlElement(name = "OfferSubTitle", required = true)
    protected String offerSubTitle;
    @XmlElement(name = "Price", defaultValue = "null")
    protected Double price;
    @XmlElement(name = "RetailPrice")
    protected String retailPrice;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "Amenities")
    protected AmenitiesType amenities;
    @XmlElement(name = "Properties")
    protected PropertiesType properties;
    @XmlElement(name = "PictureDetails", required = true)
    protected PictureDetailsType pictureDetails;
    @XmlElement(name = "AdditionalOptions")
    protected AdditionalOptionsType additionalOptions;
    @XmlElement(name = "Description", required = true)
    protected DescriptionType description;
    @XmlElement(name = "DescriptionPictures", required = true)
    protected DescriptionPicturesType descriptionPictures;
    @XmlElement(name = "VoucherValidity", defaultValue = "null")
    protected Integer voucherValidity;
    @XmlElement(name = "Errors")
    protected ErrorsType errors;
    @XmlAttribute(name = "TimeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAck(String value) {
        this.ack = value;
    }

    public boolean isSetAck() {
        return (this.ack!= null);
    }

    /**
     * Gets the value of the designTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDesignTemplate() {
        return designTemplate;
    }

    /**
     * Sets the value of the designTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDesignTemplate(Integer value) {
        this.designTemplate = value;
    }

    public boolean isSetDesignTemplate() {
        return (this.designTemplate!= null);
    }

    /**
     * Gets the value of the siteId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * Sets the value of the siteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSiteId(Integer value) {
        this.siteId = value;
    }

    public boolean isSetSiteId() {
        return (this.siteId!= null);
    }

    /**
     * Gets the value of the shopObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopObjectId() {
        return shopObjectId;
    }

    /**
     * Sets the value of the shopObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopObjectId(String value) {
        this.shopObjectId = value;
    }

    public boolean isSetShopObjectId() {
        return (this.shopObjectId!= null);
    }

    /**
     * Gets the value of the templateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * Sets the value of the templateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateName(String value) {
        this.templateName = value;
    }

    public boolean isSetTemplateName() {
        return (this.templateName!= null);
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductId(Integer value) {
        this.productId = value;
    }

    public boolean isSetProductId() {
        return (this.productId!= null);
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriesType }
     *     
     */
    public CategoriesType getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriesType }
     *     
     */
    public void setCategories(CategoriesType value) {
        this.categories = value;
    }

    public boolean isSetCategories() {
        return (this.categories!= null);
    }

    /**
     * Gets the value of the storeCategories property.
     * 
     * @return
     *     possible object is
     *     {@link StoreCategoriesType }
     *     
     */
    public StoreCategoriesType getStoreCategories() {
        return storeCategories;
    }

    /**
     * Sets the value of the storeCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreCategoriesType }
     *     
     */
    public void setStoreCategories(StoreCategoriesType value) {
        this.storeCategories = value;
    }

    public boolean isSetStoreCategories() {
        return (this.storeCategories!= null);
    }

    /**
     * Gets the value of the offerTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferTitle() {
        return offerTitle;
    }

    /**
     * Sets the value of the offerTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferTitle(String value) {
        this.offerTitle = value;
    }

    public boolean isSetOfferTitle() {
        return (this.offerTitle!= null);
    }

    /**
     * Gets the value of the offerSubTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferSubTitle() {
        return offerSubTitle;
    }

    /**
     * Sets the value of the offerSubTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferSubTitle(String value) {
        this.offerSubTitle = value;
    }

    public boolean isSetOfferSubTitle() {
        return (this.offerSubTitle!= null);
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrice(Double value) {
        this.price = value;
    }

    public boolean isSetPrice() {
        return (this.price!= null);
    }

    /**
     * Gets the value of the retailPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetailPrice() {
        return retailPrice;
    }

    /**
     * Sets the value of the retailPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetailPrice(String value) {
        this.retailPrice = value;
    }

    public boolean isSetRetailPrice() {
        return (this.retailPrice!= null);
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    public boolean isSetCurrency() {
        return (this.currency!= null);
    }

    /**
     * Gets the value of the amenities property.
     * 
     * @return
     *     possible object is
     *     {@link AmenitiesType }
     *     
     */
    public AmenitiesType getAmenities() {
        return amenities;
    }

    /**
     * Sets the value of the amenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmenitiesType }
     *     
     */
    public void setAmenities(AmenitiesType value) {
        this.amenities = value;
    }

    public boolean isSetAmenities() {
        return (this.amenities!= null);
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    public boolean isSetProperties() {
        return (this.properties!= null);
    }

    /**
     * Gets the value of the pictureDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PictureDetailsType }
     *     
     */
    public PictureDetailsType getPictureDetails() {
        return pictureDetails;
    }

    /**
     * Sets the value of the pictureDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PictureDetailsType }
     *     
     */
    public void setPictureDetails(PictureDetailsType value) {
        this.pictureDetails = value;
    }

    public boolean isSetPictureDetails() {
        return (this.pictureDetails!= null);
    }

    /**
     * Gets the value of the additionalOptions property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalOptionsType }
     *     
     */
    public AdditionalOptionsType getAdditionalOptions() {
        return additionalOptions;
    }

    /**
     * Sets the value of the additionalOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalOptionsType }
     *     
     */
    public void setAdditionalOptions(AdditionalOptionsType value) {
        this.additionalOptions = value;
    }

    public boolean isSetAdditionalOptions() {
        return (this.additionalOptions!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDescription(DescriptionType value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the descriptionPictures property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionPicturesType }
     *     
     */
    public DescriptionPicturesType getDescriptionPictures() {
        return descriptionPictures;
    }

    /**
     * Sets the value of the descriptionPictures property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionPicturesType }
     *     
     */
    public void setDescriptionPictures(DescriptionPicturesType value) {
        this.descriptionPictures = value;
    }

    public boolean isSetDescriptionPictures() {
        return (this.descriptionPictures!= null);
    }

    /**
     * Gets the value of the voucherValidity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVoucherValidity() {
        return voucherValidity;
    }

    /**
     * Sets the value of the voucherValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVoucherValidity(Integer value) {
        this.voucherValidity = value;
    }

    public boolean isSetVoucherValidity() {
        return (this.voucherValidity!= null);
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    public boolean isSetErrors() {
        return (this.errors!= null);
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    public boolean isSetTimeStamp() {
        return (this.timeStamp!= null);
    }

}
