//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:31:02 PM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OfferText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OfferAdditionalText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VoucherText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VoucherValidityText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptionType", propOrder = {
    "title",
    "subTitle",
    "offerText",
    "offerAdditionalText",
    "voucherText",
    "voucherValidityText"
})
public class DescriptionType
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "SubTitle")
    protected String subTitle;
    @XmlElement(name = "OfferText")
    protected String offerText;
    @XmlElement(name = "OfferAdditionalText")
    protected String offerAdditionalText;
    @XmlElement(name = "VoucherText")
    protected String voucherText;
    @XmlElement(name = "VoucherValidityText")
    protected String voucherValidityText;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title!= null);
    }

    /**
     * Gets the value of the subTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * Sets the value of the subTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubTitle(String value) {
        this.subTitle = value;
    }

    public boolean isSetSubTitle() {
        return (this.subTitle!= null);
    }

    /**
     * Gets the value of the offerText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferText() {
        return offerText;
    }

    /**
     * Sets the value of the offerText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferText(String value) {
        this.offerText = value;
    }

    public boolean isSetOfferText() {
        return (this.offerText!= null);
    }

    /**
     * Gets the value of the offerAdditionalText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferAdditionalText() {
        return offerAdditionalText;
    }

    /**
     * Sets the value of the offerAdditionalText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferAdditionalText(String value) {
        this.offerAdditionalText = value;
    }

    public boolean isSetOfferAdditionalText() {
        return (this.offerAdditionalText!= null);
    }

    /**
     * Gets the value of the voucherText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherText() {
        return voucherText;
    }

    /**
     * Sets the value of the voucherText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherText(String value) {
        this.voucherText = value;
    }

    public boolean isSetVoucherText() {
        return (this.voucherText!= null);
    }

    /**
     * Gets the value of the voucherValidityText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherValidityText() {
        return voucherValidityText;
    }

    /**
     * Sets the value of the voucherValidityText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherValidityText(String value) {
        this.voucherValidityText = value;
    }

    public boolean isSetVoucherValidityText() {
        return (this.voucherValidityText!= null);
    }

}
