//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:31:02 PM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescriptionPicturesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptionPicturesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DescriptionPictureURL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OfferSliderPictureURL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptionPicturesType", propOrder = {
    "descriptionPictureURL",
    "offerSliderPictureURL"
})
public class DescriptionPicturesType
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "DescriptionPictureURL")
    protected List<String> descriptionPictureURL;
    @XmlElement(name = "OfferSliderPictureURL")
    protected List<String> offerSliderPictureURL;

    /**
     * Gets the value of the descriptionPictureURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionPictureURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionPictureURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDescriptionPictureURL() {
        if (descriptionPictureURL == null) {
            descriptionPictureURL = new ArrayList<String>();
        }
        return this.descriptionPictureURL;
    }

    public boolean isSetDescriptionPictureURL() {
        return ((this.descriptionPictureURL!= null)&&(!this.descriptionPictureURL.isEmpty()));
    }

    public void unsetDescriptionPictureURL() {
        this.descriptionPictureURL = null;
    }

    /**
     * Gets the value of the offerSliderPictureURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerSliderPictureURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferSliderPictureURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOfferSliderPictureURL() {
        if (offerSliderPictureURL == null) {
            offerSliderPictureURL = new ArrayList<String>();
        }
        return this.offerSliderPictureURL;
    }

    public boolean isSetOfferSliderPictureURL() {
        return ((this.offerSliderPictureURL!= null)&&(!this.offerSliderPictureURL.isEmpty()));
    }

    public void unsetOfferSliderPictureURL() {
        this.offerSliderPictureURL = null;
    }

}
