//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:31:02 PM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InformationsTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformationsTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FAQ" type="{}FAQType" minOccurs="0"/>
 *         &lt;element name="TermsAndConditions" type="{}TermsAndConditionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformationsTypes", propOrder = {
    "faq",
    "termsAndConditions"
})
public class InformationsTypes
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "FAQ")
    protected FAQType faq;
    @XmlElement(name = "TermsAndConditions")
    protected TermsAndConditionsType termsAndConditions;

    /**
     * Gets the value of the faq property.
     * 
     * @return
     *     possible object is
     *     {@link FAQType }
     *     
     */
    public FAQType getFAQ() {
        return faq;
    }

    /**
     * Sets the value of the faq property.
     * 
     * @param value
     *     allowed object is
     *     {@link FAQType }
     *     
     */
    public void setFAQ(FAQType value) {
        this.faq = value;
    }

    public boolean isSetFAQ() {
        return (this.faq!= null);
    }

    /**
     * Gets the value of the termsAndConditions property.
     * 
     * @return
     *     possible object is
     *     {@link TermsAndConditionsType }
     *     
     */
    public TermsAndConditionsType getTermsAndConditions() {
        return termsAndConditions;
    }

    /**
     * Sets the value of the termsAndConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermsAndConditionsType }
     *     
     */
    public void setTermsAndConditions(TermsAndConditionsType value) {
        this.termsAndConditions = value;
    }

    public boolean isSetTermsAndConditions() {
        return (this.termsAndConditions!= null);
    }

}
