//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:31:02 PM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TotalNoOfImages" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Images" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Image" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ThumbnailURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Dimensions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Errors" type="{}ErrorsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ack",
    "objectId",
    "totalNoOfImages",
    "images",
    "errors"
})
@XmlRootElement(name = "ListOfPicturesRS")
public class ListOfPicturesRS
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "Ack", required = true)
    protected String ack;
    @XmlElement(name = "ObjectId")
    protected Integer objectId;
    @XmlElement(name = "TotalNoOfImages")
    protected Integer totalNoOfImages;
    @XmlElement(name = "Images")
    protected ListOfPicturesRS.Images images;
    @XmlElement(name = "Errors")
    protected ErrorsType errors;
    @XmlAttribute(name = "TimeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAck(String value) {
        this.ack = value;
    }

    public boolean isSetAck() {
        return (this.ack!= null);
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObjectId(Integer value) {
        this.objectId = value;
    }

    public boolean isSetObjectId() {
        return (this.objectId!= null);
    }

    /**
     * Gets the value of the totalNoOfImages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalNoOfImages() {
        return totalNoOfImages;
    }

    /**
     * Sets the value of the totalNoOfImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalNoOfImages(Integer value) {
        this.totalNoOfImages = value;
    }

    public boolean isSetTotalNoOfImages() {
        return (this.totalNoOfImages!= null);
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPicturesRS.Images }
     *     
     */
    public ListOfPicturesRS.Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPicturesRS.Images }
     *     
     */
    public void setImages(ListOfPicturesRS.Images value) {
        this.images = value;
    }

    public boolean isSetImages() {
        return (this.images!= null);
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    public boolean isSetErrors() {
        return (this.errors!= null);
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    public boolean isSetTimeStamp() {
        return (this.timeStamp!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Image" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ThumbnailURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Dimensions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "image"
    })
    public static class Images
        implements Serializable
    {

        private final static long serialVersionUID = 20070801L;
        @XmlElement(name = "Image")
        protected List<ListOfPicturesRS.Images.Image> image;

        /**
         * Gets the value of the image property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the image property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ListOfPicturesRS.Images.Image }
         * 
         * 
         */
        public List<ListOfPicturesRS.Images.Image> getImage() {
            if (image == null) {
                image = new ArrayList<ListOfPicturesRS.Images.Image>();
            }
            return this.image;
        }

        public boolean isSetImage() {
            return ((this.image!= null)&&(!this.image.isEmpty()));
        }

        public void unsetImage() {
            this.image = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ThumbnailURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Dimensions" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imageId",
            "name",
            "url",
            "thumbnailURL",
            "dimensions"
        })
        public static class Image
            implements Serializable
        {

            private final static long serialVersionUID = 20070801L;
            @XmlElement(name = "ImageId")
            protected int imageId;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "URL", required = true)
            protected String url;
            @XmlElement(name = "ThumbnailURL", required = true)
            protected String thumbnailURL;
            @XmlElement(name = "Dimensions", required = true)
            protected String dimensions;

            /**
             * Gets the value of the imageId property.
             * 
             */
            public int getImageId() {
                return imageId;
            }

            /**
             * Sets the value of the imageId property.
             * 
             */
            public void setImageId(int value) {
                this.imageId = value;
            }

            public boolean isSetImageId() {
                return true;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            public boolean isSetName() {
                return (this.name!= null);
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getURL() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setURL(String value) {
                this.url = value;
            }

            public boolean isSetURL() {
                return (this.url!= null);
            }

            /**
             * Gets the value of the thumbnailURL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getThumbnailURL() {
                return thumbnailURL;
            }

            /**
             * Sets the value of the thumbnailURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setThumbnailURL(String value) {
                this.thumbnailURL = value;
            }

            public boolean isSetThumbnailURL() {
                return (this.thumbnailURL!= null);
            }

            /**
             * Gets the value of the dimensions property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDimensions() {
                return dimensions;
            }

            /**
             * Sets the value of the dimensions property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDimensions(String value) {
                this.dimensions = value;
            }

            public boolean isSetDimensions() {
                return (this.dimensions!= null);
            }

        }

    }

}
