//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:31:02 PM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuthenticationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SourceId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Voucher" type="{}VoucherType" minOccurs="0"/>
 *         &lt;element name="Settings" type="{}SettingsType" minOccurs="0"/>
 *         &lt;element name="LogoPictureURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectSlider" type="{}objsliderpics"/>
 *         &lt;element name="Map" type="{}MapType"/>
 *         &lt;element name="PaymentOptions" type="{}PaymentOptionsType"/>
 *         &lt;element name="InformationTypes" type="{}InformationsTypes"/>
 *         &lt;element name="ErrorLang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authenticationCode",
    "sourceId",
    "channelId",
    "objectId",
    "voucher",
    "settings",
    "logoPictureURL",
    "objectSlider",
    "map",
    "paymentOptions",
    "informationTypes",
    "errorLang"
})
@XmlRootElement(name = "ObjectConfigurationRQ")
public class ObjectConfigurationRQ
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "AuthenticationCode", required = true)
    protected String authenticationCode;
    @XmlElement(name = "SourceId")
    protected int sourceId;
    @XmlElement(name = "ChannelId")
    protected int channelId;
    @XmlElement(name = "ObjectId")
    protected int objectId;
    @XmlElement(name = "Voucher")
    protected VoucherType voucher;
    @XmlElement(name = "Settings")
    protected SettingsType settings;
    @XmlElement(name = "LogoPictureURL", required = true)
    protected String logoPictureURL;
    @XmlElement(name = "ObjectSlider", required = true)
    protected Objsliderpics objectSlider;
    @XmlElement(name = "Map", required = true)
    protected MapType map;
    @XmlElement(name = "PaymentOptions", required = true)
    protected PaymentOptionsType paymentOptions;
    @XmlElement(name = "InformationTypes", required = true)
    protected InformationsTypes informationTypes;
    @XmlElement(name = "ErrorLang", required = true)
    protected String errorLang;
    @XmlAttribute(name = "TimeStamp")
    protected String timeStamp;

    /**
     * Gets the value of the authenticationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationCode() {
        return authenticationCode;
    }

    /**
     * Sets the value of the authenticationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationCode(String value) {
        this.authenticationCode = value;
    }

    public boolean isSetAuthenticationCode() {
        return (this.authenticationCode!= null);
    }

    /**
     * Gets the value of the sourceId property.
     * 
     */
    public int getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     */
    public void setSourceId(int value) {
        this.sourceId = value;
    }

    public boolean isSetSourceId() {
        return true;
    }

    /**
     * Gets the value of the channelId property.
     * 
     */
    public int getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     */
    public void setChannelId(int value) {
        this.channelId = value;
    }

    public boolean isSetChannelId() {
        return true;
    }

    /**
     * Gets the value of the objectId property.
     * 
     */
    public int getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(int value) {
        this.objectId = value;
    }

    public boolean isSetObjectId() {
        return true;
    }

    /**
     * Gets the value of the voucher property.
     * 
     * @return
     *     possible object is
     *     {@link VoucherType }
     *     
     */
    public VoucherType getVoucher() {
        return voucher;
    }

    /**
     * Sets the value of the voucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoucherType }
     *     
     */
    public void setVoucher(VoucherType value) {
        this.voucher = value;
    }

    public boolean isSetVoucher() {
        return (this.voucher!= null);
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link SettingsType }
     *     
     */
    public SettingsType getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettingsType }
     *     
     */
    public void setSettings(SettingsType value) {
        this.settings = value;
    }

    public boolean isSetSettings() {
        return (this.settings!= null);
    }

    /**
     * Gets the value of the logoPictureURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoPictureURL() {
        return logoPictureURL;
    }

    /**
     * Sets the value of the logoPictureURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoPictureURL(String value) {
        this.logoPictureURL = value;
    }

    public boolean isSetLogoPictureURL() {
        return (this.logoPictureURL!= null);
    }

    /**
     * Gets the value of the objectSlider property.
     * 
     * @return
     *     possible object is
     *     {@link Objsliderpics }
     *     
     */
    public Objsliderpics getObjectSlider() {
        return objectSlider;
    }

    /**
     * Sets the value of the objectSlider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Objsliderpics }
     *     
     */
    public void setObjectSlider(Objsliderpics value) {
        this.objectSlider = value;
    }

    public boolean isSetObjectSlider() {
        return (this.objectSlider!= null);
    }

    /**
     * Gets the value of the map property.
     * 
     * @return
     *     possible object is
     *     {@link MapType }
     *     
     */
    public MapType getMap() {
        return map;
    }

    /**
     * Sets the value of the map property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapType }
     *     
     */
    public void setMap(MapType value) {
        this.map = value;
    }

    public boolean isSetMap() {
        return (this.map!= null);
    }

    /**
     * Gets the value of the paymentOptions property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentOptionsType }
     *     
     */
    public PaymentOptionsType getPaymentOptions() {
        return paymentOptions;
    }

    /**
     * Sets the value of the paymentOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentOptionsType }
     *     
     */
    public void setPaymentOptions(PaymentOptionsType value) {
        this.paymentOptions = value;
    }

    public boolean isSetPaymentOptions() {
        return (this.paymentOptions!= null);
    }

    /**
     * Gets the value of the informationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link InformationsTypes }
     *     
     */
    public InformationsTypes getInformationTypes() {
        return informationTypes;
    }

    /**
     * Sets the value of the informationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationsTypes }
     *     
     */
    public void setInformationTypes(InformationsTypes value) {
        this.informationTypes = value;
    }

    public boolean isSetInformationTypes() {
        return (this.informationTypes!= null);
    }

    /**
     * Gets the value of the errorLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorLang() {
        return errorLang;
    }

    /**
     * Sets the value of the errorLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorLang(String value) {
        this.errorLang = value;
    }

    public boolean isSetErrorLang() {
        return (this.errorLang!= null);
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    public boolean isSetTimeStamp() {
        return (this.timeStamp!= null);
    }

}
