//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:31:02 PM IST 
//


package com.cultuzz.channel.XMLpojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentOptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PaymentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MarketPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="changePaymentId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentOptionType", propOrder = {
    "paymentType",
    "paymentId",
    "marketPlace"
})
public class PaymentOptionType
    implements Serializable
{

    private final static long serialVersionUID = 20070801L;
    @XmlElement(name = "PaymentType", required = true)
    protected String paymentType;
    @XmlElement(name = "PaymentId", required = true)
    protected String paymentId;
    @XmlElement(name = "MarketPlace", required = true)
    protected String marketPlace;
    @XmlAttribute(name = "changePaymentId")
    protected String changePaymentId;

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

    public boolean isSetPaymentType() {
        return (this.paymentType!= null);
    }

    /**
     * Gets the value of the paymentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * Sets the value of the paymentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentId(String value) {
        this.paymentId = value;
    }

    public boolean isSetPaymentId() {
        return (this.paymentId!= null);
    }

    /**
     * Gets the value of the marketPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketPlace() {
        return marketPlace;
    }

    /**
     * Sets the value of the marketPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketPlace(String value) {
        this.marketPlace = value;
    }

    public boolean isSetMarketPlace() {
        return (this.marketPlace!= null);
    }

    /**
     * Gets the value of the changePaymentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangePaymentId() {
        return changePaymentId;
    }

    /**
     * Sets the value of the changePaymentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangePaymentId(String value) {
        this.changePaymentId = value;
    }

    public boolean isSetChangePaymentId() {
        return (this.changePaymentId!= null);
    }

}
