//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 11:35:44 AM IST 
//


package com.cultuzz.XMLPojos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="VorlageId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;sequence>
 *             &lt;element name="ItemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="CzId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="ThemeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="preview" type="{}myboolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vorlageId",
    "itemId",
    "czId",
    "themeId",
    "languageId"
})
@XmlRootElement(name = "VoucherCreationRQ")
public class VoucherCreationRQ {

    @XmlElement(name = "VorlageId")
    protected Integer vorlageId;
    @XmlElement(name = "ItemId")
    protected String itemId;
    @XmlElement(name = "CzId")
    protected String czId;
    @XmlElement(name = "ThemeId")
    protected int themeId;
    @XmlElement(name = "LanguageId")
    protected Byte languageId;
    @XmlAttribute(name = "preview")
    @XmlJavaTypeAdapter(JaxbBooleanAdapter.class)
    protected Boolean preview;

    /**
     * Gets the value of the vorlageId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVorlageId() {
        return vorlageId;
    }

    /**
     * Sets the value of the vorlageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVorlageId(Integer value) {
        this.vorlageId = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemId(String value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the czId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCzId() {
        return czId;
    }

    /**
     * Sets the value of the czId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCzId(String value) {
        this.czId = value;
    }

    /**
     * Gets the value of the themeId property.
     * 
     */
    public int getThemeId() {
        return themeId;
    }

    /**
     * Sets the value of the themeId property.
     * 
     */
    public void setThemeId(int value) {
        this.themeId = value;
    }

    /**
     * Gets the value of the languageId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLanguageId() {
        return languageId;
    }

    /**
     * Sets the value of the languageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLanguageId(Byte value) {
        this.languageId = value;
    }

    /**
     * Gets the value of the preview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Boolean isPreview() {
        return preview;
    }

    /**
     * Sets the value of the preview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreview(Boolean value) {
        this.preview = value;
    }

}
